レイアウトの調整
ios-osushi/website pull request #44
Opened 2022-05-02 14:01 UTC by uhooi

2022-05-02 16:15 UTC, treastrain requested changes

2022-05-02 16:15 UTC, treastrain commented on Resources/IosOsushiTheme/styles.css
> +    background-color: #eee;
このままだとダークテーマの場合に文字色と近すぎるために読みにくくなってしまいます…

![スクリーンショット 2022-05-03 1 14 57](https://user-images.githubusercontent.com/13805382/166268706-22a6c226-5f36-4693-8703-dc065ac5e551.png)

2022-05-02 16:21 UTC, crane-hiromu commented on Resources/IosOsushiTheme/styles.css
> +    margin-bottom: 20px;
bottom はそんなにあけなくてもええんでないかね（個人的主観だけど~）

2022-05-02 16:24 UTC, uhooi commented on Resources/IosOsushiTheme/styles.css
> +    background-color: #eee;
ダークモード対応を失念していた、、
これでどうだ！？ https://github.com/ios-osushi/website/pull/44/commits/9ab8e1ca5c9bcd244a86a04eda3907fab1e21045
![スクリーンショット 2022-05-03 1 22 18](https://user-images.githubusercontent.com/21194714/166270033-523c250a-448e-4d6c-b0fe-3d0ece906b61.png)

2022-05-02 16:30 UTC, uhooi commented on Resources/IosOsushiTheme/styles.css
> +    margin-bottom: 20px;
それは確かに気になっていた
5 px 縮めたけどどうだろう？ https://github.com/ios-osushi/website/pull/44/commits/7c9992bde2e05312037b3f91b6ae4b9b3fe99291

2022-05-07 11:01 UTC, treastrain commented on Resources/IosOsushiTheme/styles.css
> +    background-color: #eee;
よさそうです！

2022-05-07 11:01 UTC, treastrain approved these changes

2022-05-07 11:04 UTC, merged

2022-05-07 11:04 UTC, uhooi commented on Resources/IosOsushiTheme/styles.css
> +    margin-bottom: 20px;
一旦マージした〜
もし気になったら別に Issue 立てるね！