Create 006-20220509.md
ios-osushi/website pull request #48
Opened 2022-05-07 13:25 UTC by treastrain

# スクリーンショット

|`006-20220509.md`|
|:--:|
|![Web キャプチャ_7-5-2022_22239_localhost](https://user-images.githubusercontent.com/13805382/167256311-a2af83fd-b69a-45e4-9835-751d6fdeaa80.jpeg)|

2022-05-07 14:05 UTC, uhooi requested changes

2022-05-07 14:05 UTC, uhooi commented on Content/posts/006-20220509.md
> +iOS 関連の技術を主テーマとした、技術者のためのカンファレンスである [iOSDC Japan 2022](https://iosdc.jp/2022/) のティザーが公開されました。2022年8月27日から29日までの日程で、オフラインとオンラインのハイブリッド開催となる模様です。
細かいけど文言を調整してみた↓

```suggestion
iOS 関連の技術を主なテーマとした、技術者のためのカンファレンスである [iOSDC Japan 2022](https://iosdc.jp/2022/) のティザーサイトが公開されました。2022年8月27日から29日までの日程で、オフラインとオンラインのハイブリッド開催です。
```

2022-05-07 14:05 UTC, uhooi commented on Content/posts/006-20220509.md
> +## Firebase Apple SDK (旧称 iOS SDK) のメジャーアップデートがリリース
[修正任意]
見出しはスッキリしたほうがいいから、旧称はなくていいと思う！（概要も同様）
書くなら本文かな！

あとバージョンを明記していいと思う！

```suggestion
## Firebase Apple SDK 9.0.0 リリース
```

2022-05-07 14:05 UTC, uhooi commented on Content/posts/006-20220509.md
> +
2 行以上の空白行はいらないと思う！

```suggestion
```

2022-05-07 14:27 UTC, treastrain commented on Content/posts/006-20220509.md
> +## Firebase Apple SDK (旧称 iOS SDK) のメジャーアップデートがリリース
@uhooi 

iOS SDK → Apple SDK に名称変更後 初のメジャーアップデートだったので、今回に限っては「旧称」と入れたかった次第ですね。場所を本文に移しました！

タイトル部分へのバージョン番号明記は、今回の場合は避けたいと考えています。
理由は「著名 OSS のリリース情報」セクションではバージョン番号がタイトル3としてあり、同じような表記が重複してしまう点、「バージョン番号が変わったこと」よりも「マイナーアップデートではなくてメジャーアップデートであること」を伝えたいという意図を強く示したい（Semantic Versioning を理解している方々へはバージョン番号の表記のみで済むとは思いますが…^^;）という点の2つです。

https://github.com/ios-osushi/website/pull/48/commits/e7c1f664173380865032b7cce0a3a11fd5cabde5 で対応しました！

2022-05-07 15:37 UTC, uhooi commented on Content/posts/006-20220509.md
> +## Firebase Apple SDK (旧称 iOS SDK) のメジャーアップデートがリリース
理解…！
いろいろ考えてくれてありがとう、OK です 🙆

2022-05-07 15:37 UTC, uhooi approved these changes

2022-05-08 06:18 UTC, treastrain commented
レビューありがとうございました！

2022-05-08 06:18 UTC, merged